name: _GET_VERSION_URL

on:
  workflow_dispatch:

jobs:
  get-version-url:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: '472.0.0'

      - name: Get GAE URL
        id: getGAEURL
        run: |
          VERSION_NAME=$(echo ${{ github.ref_name }} | perl -pe "s/[^A-Za-z0-9\n]/-/g;" | cut -c 1-63)
          OUTPUT=$(gcloud app versions list --filter="id=$VERSION_NAME" --uri)
          echo "Command Output: $OUTPUT"
          if [[ "$OUTPUT" == "Listed 0 items." ]]; then
            echo "No URL Found, Setting Default URL"
            echo "apiUrl=https://gcp-test-420611.an.r.appspot.com" >> $GITHUB_OUTPUT
          else
            echo "Found version, setting Version URL"
            echo "apiUrl=$OUTPUT" >> $GITHUB_OUTPUT
          fi

      - name: Display URL
        run: echo "${{ steps.getGAEURL.outputs.apiUrl }}"

      - name: Build with Default calchez-backend URL
        if: steps.getGAEURL.outputs.apiUrl == 'https://gcp-test-420611.an.r.appspot.com'
        run: |
          echo "Build with Default URL!"

      - name: Build with Specific calchez-backend URL
        if: steps.getGAEURL.outputs.apiUrl != 'https://gcp-test-420611.an.r.appspot.com'
        run: |
          echo "Build with Specific URL"