name: _GET_VERSION_URI

on:
  workflow_dispatch:

jobs:
  get-version-uri:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GAE URI
        id: getGAEURI
        run: |
          VERSION_NAME=$(echo ${{ github.ref_name }} | perl -pe "s/[^A-Za-z0-9\n]/-/g;" | cut -c 1-63)
          EXPECTED_URI="https://$VERSION_NAME-dot-gcp-test-420611.an.r.appspot.com"
          VERSION_URI=$(gcloud app versions list --filter="id=$VERSION_NAME" --uri)
          if [[ "$VERSION_URI" == "$EXPECTED_URI" ]]; then
            echo "Found version, setting Version URI"
            echo "apiUri=$VERSION_URI" >> $GITHUB_OUTPUT
          else
            echo "No version found, setting default URI"
            echo "apiUri=https://gcp-test-420611.an.r.appspot.com" >> $GITHUB_OUTPUT
          fi

      - name: Display URI
        run: echo "${{ steps.getGAEURI.outputs.apiUri }}"
