name: _GET_VERSION_URI

on:
  workflow_dispatch:

jobs:
  generate-version-name:
    name: Generate Version Name
    uses: ./.github/workflows/_generate-version-name.yml
    with:
      BRANCH_NAME: ${{ github.ref_name }}

  get-version-uri:
    runs-on: ubuntu-latest
    needs:
      - generate-version-name
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Get GAE URI
        id: getGAEURI
        run: |
          VERSION_URI=$(gcloud app versions list --filter="id=${{ needs.generate-version-name.outputs.version_name }}" --uri)
          if [[ "$VERSION_URI" == "Listed 0 items." ]]; then
            echo "No version found, setting default URI"
            echo "apiDomain=https://gcp-test-420611.an.r.appspot.com" >> $GITHUB_OUTPUT
          else
            echo "Found version, setting Version URI"
            echo "apiDomain=$VERSION_URI" >> $GITHUB_OUTPUT
          fi

      - name: Display URI
        run: echo ${{ steps.getGAEVersionURI.outputs.result }}
