name: DEPLOY_PREVIEW_VERSION

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - develop

jobs:
  generate-version-name:
    name: Generate Version Name
    uses: ./.github/workflows/_generate-version-name.yml
    with:
      BRANCH_NAME: ${{ github.head_ref }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - generate-version-name
    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Create Version Name from Branch Name
        id: create_version_name
        uses: actions/github-script@v6
        env:
          BRANCH_NAME: ${{ github.head_ref }}
        with:
          result-encoding: string
          script: |
            try {
              const versionName = process.env.BRANCH_NAME.replaceAll('/', '-')
              return versionName
            } catch (error) {
              core.error("Failed to create version name")
              core.setFailed(error)
            }

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy
        run: gcloud app deploy --quiet --no-promote --project=gcp-test-420611 --version=${{ needs.generate-version-name.outputs.version_name }}
